language: node_js
node_js:
  - 6.5.0
  - 8
  - 10
  - 11
os:
  - windows
  - osx
  - linux
dist: xenial
script: npm test
# When pushing a tagged commit, Travis adds two builds: one with the tag, one
# without. We only want to build the one with the tag, because it's the one
# that runs the deployment stage
if: '!(commit_message =~ /^Release/ && tag is blank)'
jobs:
  include:
    # Test coverage check must happen after tests for the whole matrix have
    # been performed, so we get the merged coverage map
    - stage: Coverage check
      os: linux
      node_js: 11
      script: gulp coverage
      # If CI fails, codecov does not post a bot comment on PR, so we skip it
      if: type != pull_request && (branch == master || tag is not blank)
    # Deployment must happen after tests for the whole matrix have been
    # performed, so we use `jobs.include` with a different `stage`
    - stage: Deploy
      os: linux
      node_js: 11
      # We have already run tests
      script: gulp build
      if: tag is not blank
      # We run `release-it` locally (which tagged the commit and create a
      # GitHub release) but we publish to npm only after CI success.
      deploy:
        provider: npm
        email: ehmicky@gmail.com
        api_key:
          secure: W8H0umaA0ZMzz9jk9CG9/FE+tzE5EDR8YiflteffNjJLmAJP2QvqL7HIKWy2NgvajKnRwu00gn/KgVmVds119dBcMEq54u4jZO+om6/5d2/epyCUpALFsIREBkAYB1LMHA6EjVdZa8BllNfS1bcrigej4LCy9tI/NOQCIAsklVpn/tWMfX+zdbc9kQMirPnkRJkx4joAKSN2Q0BV9Kw7/ANIu6id8Vs4VyWdTDejMY262yFG8Jyof2qG08Rl56fj/ij1poZWQd+DUr/JCNX7huxdKX6PBAYutBlmm68bo/tQcuNJJBzlsbHM9xMLY/4ShPLdgWnKk2gPVlZq7z953w1GucX8SCHVYwe2X27WRyTdvF7HWmww5tLTTiP02DjQdFGzyB6tlFwhHYg39nrmEUGcEbU7gEjdQAEK1yYpIHhwQvrdFaJof8dcbs6mdAAo2Du2BabmS/v8v0/ieChMT8EMk/Wp9tRKLOTvFYnzpJ0KanM9fe5eOfNN4H5/bAMeeJLTnvbno92JouC8nzJtE452qrTn2RJ4TRXOfJx+g1pbHYNoM8ro/PCOZD8zDBD8qnv0/tytn+h8dzXDAG/hTnRVqpFM7GR6h+uOFqFV75wF1yIsZ8yCjMUEI0jbOecT13E9b6u23IUZHWB7mZjcY1XlmI2mz+LdoQHaeDX+FsQ=
        on:
          tags: true
        # We want to run install step and keep built files for release
        skip_cleanup: true
cache: npm
notifications:
  webhooks:
    - https://www.travisbuddy.com?only=failed,errored&insertMode=update
  email: false
