language: node_js
node_js: '11'
dist: xenial
# When pushing a tagged commit, Travis adds two builds: one with the tag, one
# without. We only want to build the one with the tag, because it's the one
# that runs the deployment stage
if: '!(commit_message =~ /^Release/ && tag is blank)'
jobs:
  include:
    # Test on Windows/Mac/Linux using latest Node.js.
    # Also test on Linux with older Node.js versions.
    # We do not run each possible combination to make CI faster.
    - os: windows
    - os: osx
    - node_js: '8.10.0'
    - node_js: '10'
    - node_js: '11'
    # Test coverage check must happen after tests for the whole matrix have
    # been performed, so we get the merged coverage map
    - stage: Coverage check
      # If this fails during a PR, CI will fail. However when CI fails, codecov
      # does not post any comment. Since codecov comments are nicer than
      # Travis Buddy comments for this, we skip it during PRs. Also this makes
      # PRs checks faster.
      if: type != pull_request
      script: gulp coverage
    # Deployment must happen after tests for the whole matrix have been
    # performed, so we use `jobs.include` with a different `stage`.
    - stage: Deploy
      if: type != pull_request && branch == master && tag is not blank
      script: gulp publish
      # NPM_TOKEN environment variable
      env:
        secure: "RDf8D2LcKDfD6TKwlpbmhhcdET8eGSNSwnL4TNJelleonWllUQkFdaH7Q221FPpIJm5VieVQ21A1+lremkyp2/yAQ9KX8HTfTPU8cEpNKT/a5sTeOF+BmNlKjW/sEK//AO49bMbR7WI0e90ct9IbF0iSge1q3x2pD4+3TqcKTThcnTETNEmW4sRGOz+HSWRONs0gjyTyXOKakFFTcDp1Oiif+0ZE7A9SiWnSijO2+4py1Em3PTDCx1f/FKtfDQbynZIlkM1l8h1eR3D2qUOWZ3r5UBgnLi3JQxl96zCWg148qYVO13nko27QGaZRnqktscZWY4+tKNO8z6eFa5r5DuYc+J4+vq0xcRd0bfckgdpf/gS7gaUxKTScD2TeeEjlHIE1BXhJKqbYjgiH46TrLWiGs38kvKSvebwBoAY9CPXbj6VMMvE0WUmFAg/DBdUd40hnIlW+8cf+w0p+wSlPBDtMhptlLePCsqCfLI2g82tsyVcGnrg3JMsYh1MA5V5QhY28rCnPkyBfhpyon4pSOCSWXy+YTChohiBmakwf4yFssE5Tfbeae0EFJtfJ6YQ0iAkqUgnuHtGUuMYXA6yaE7GJ7DzXldQUNY0KRqWTk0KouRFLGBQ4jbx3yLS+1GWXmT87/8MY8g2Q34/fKyvEZELl6Th7V4rS5i59Pe16SeY="
notifications:
  webhooks:
    - https://www.travisbuddy.com?only=failed,errored&insertMode=update
  email: false
# We do not use `cache: npm` because downloading and uploading the cache
# actually takes more time than it saves during `npm ci`.
